name: wow_talent_calculator
description: A package that handles the wow talent calculator logic.
version: 1.0.1
homepage: https://github.com/oppahansi/wow_talent_calculator

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
